
vm_name: ""
vm_memory: 8192
vm_cpu: 4
vm_disk: windowsAzizTest.qcow2
vm_disk_volume: 21474836480 #20GB
vm_disk_pool: aziz_storage
vm_disk_path: /mnt/storage/aziz/windowsAzizTest.qcow2
windows_iso: /home/admin/Downloads/Win10_22H2_English_x64v1.iso
virtio_iso: /home/admin/Downloads/virtio-win-0.1.240.iso
image_path: /mnt/storage/aziz
vm_network: default

vm_static_ip: "192.168.70.60"
vm_gateway: "192.168.70.1"
vm_dns: "8.8.8.8,8.8.4.4"

win_user: "Administrator"
win_password: "windowsAziz"

