vm_name: windowsAziz
vm_memory: 8192
vm_cpu: 4
vm_disk: /mnt/storage/aziz/windowsAziz.qcow2
vm_disk_volume: 40G
windows_iso: /home/admin/Downloads/Win10_22H2_English_x64v1.iso
virtio_iso: /home/admin/Downloads/virtio-win-0.1.240.iso
image_path: /mnt/storage/aziz
vm_network: default
vm_static_ip: "192.168.70.60"
vm_gateway: "192.168.70.1"
vm_dns: "8.8.8.8,8.8.4.4"
admin_password: "windowsAziz"

win_user: "Administrator"
win_password: "windowsAziz"
win_connection: winrm
win_cert_validation: ignore
win_transport: ntlm
