- name: Install Splunk Universal Forwarder MSI
  ansible.windows.win_package:
    path: 'C:\temp\splunk_install\splunk.msi'
    state: present
    arguments:
      - /quiet
      - AGREETOLICENSE=Yes
      - LAUNCHSPLUNK=0
      - MGMT_PORT=8089
