---
- name: Check Agent version
  win_command: '"C:\Program Files (x86)\ossec-agent\wazuh-agent.exe" -V' #to be updated
  register: agent_version

- name: Show Agent version
  debug:
    var: agent_version.stdout

