---

- name: Install agent
  ansible.windows.win_package:
    path: "{{ installer_dest }}\\{{ installer_filename }}"
    state: present
    arguments: "{{ arguments | join(' ') }} INSTALLDIR=\"{{ install_dir }}\""
