---

- name:	Install Agent
  win_package:
    path: "{{agent_installer_dest }}\\{{ agent_folder }}\\{{ agent_msi }}"
    state: present
    arguments: >
      /quiet
      SERVER=127.0.0.1
      SERVERACTIVE=127.0.0.1
      HOSTNAME=zabbix_aziz
