---
- name: Ensure installer directory exists
  import_tasks: create_folder.yml

- name: Download installer
  import_tasks: agent_download.yml

- name: Ensure install directory exists
  import_tasks: install_dir_check.yml

- name: Install Agent
  import_tasks: agent_install.yml

- name: Cleanup installer
  import_tasks: agent_installer_cleanup.yml
